// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/asishcse60/go-test-bible/service (interfaces: MessageService)

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMessageService is a mock of MessageService interface.
type MockMessageService struct {
	ctrl     *gomock.Controller
	recorder *MockMessageServiceMockRecorder
}

// MockMessageServiceMockRecorder is the mock recorder for MockMessageService.
type MockMessageServiceMockRecorder struct {
	mock *MockMessageService
}

// NewMockMessageService creates a new mock instance.
func NewMockMessageService(ctrl *gomock.Controller) *MockMessageService {
	mock := &MockMessageService{ctrl: ctrl}
	mock.recorder = &MockMessageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageService) EXPECT() *MockMessageServiceMockRecorder {
	return m.recorder
}

// SendChargeNotification mocks base method.
func (m *MockMessageService) SendChargeNotification(arg0 int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendChargeNotification", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SendChargeNotification indicates an expected call of SendChargeNotification.
func (mr *MockMessageServiceMockRecorder) SendChargeNotification(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendChargeNotification", reflect.TypeOf((*MockMessageService)(nil).SendChargeNotification), arg0)
}
